#!/usr/bin/env python

import re
import os

# ==================================================================
#def mons2dims():
def main():
    """Takes molecules and filters and a list of proximity to the center of the supercell, generated by the proximity() function.
    Writes new files with molecules indexed by increasing proximity to the center of the supercell."""

    directory = os.getcwd()
    monofs = os.listdir(directory)
    dimidx = 0

    for mono1 in monofs:

        if re.match('^1-[0-9]+.xyz$', mono1):

            for mono2 in monofs:
                
                if re.match('^1-[0-9]+.xyz$', mono2):

                    if mono1 < mono2:
                        dimidx +=1
                        di = "2-" + str(mono1)[2:-4] + "+" + str(mono2)[2:]

                        with open(mono1, 'r') as mf1, open(mono2, 'r') as mf2, open(di, 'w') as df:
                            
                            for l1 in mf1.readlines():
                                if l1.startswith("Monomer"):
                                    newl1 = "Dimer " + str(dimidx) + " (Monomers " + str(mono1)[2:-4] + " and " + str(mono2)[2:-4] + ")\n"
                                    df.write(newl1)
                                else:
                                    df.write(l1)
                            
                            lidx = 0 
                            for l2 in mf2.readlines():
                                lidx += 1
                                
                                if lidx <= 2:
                                    continue
                                
                                else:
                                    df.write(l2)

                        print("Dimer " + str(dimidx) + ": " + str(di) + " created from monomers " + str(mono1) + " and " + str(mono2))

    print("")

    return
# ==================================================================

if __name__ == "__main__":
    main()
