"""
Unit and regression test for the crystalatte package.
"""

# Import package, test suite, and other packages as needed
from qcelemental.testing import compare, compare_values
import crystalatte
import pytest
import subprocess

def test_input_parser():
    """Checks that the input parser function of the CrystaLattE program
    automatically assigns a name for the supercell .xyz file."""

    # Execute the main function of crystalatte and retrieve the N-mers dictionary.
    keywords = crystalatte.input_parser("crystalatte/data/cle/no_xyz.cle")

    # For debug.
    #import pprint
    #pprint.pprint(keywords)

    # Check that the .xyz name has been autogenerated.
    assert compare("crystalatte/data/cif/Ammonia.xyz", keywords['cif_output'])

    # Clean-up generated test files
    subprocess.call(["rm", "crystalatte/data/cif/Ammonia.xyz"])
